services:
  redis:
    image: redis:alpine3.21
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared_network_task_app

  mysql:
    image: mysql:9.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_USER: djangouser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - shared_network_task_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  django:
    build: .
    container_name: django-app
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: task_db
      MYSQL_USER: djangouser
      MYSQL_PASSWORD: mypassword
    depends_on:
      - mysql
      - redis
    networks:
      - shared_network_task_app
    
networks:
  shared_network_task_app:
    name: shared_network_task_app
    driver: bridge
